### DISCUSSION TITLE
Gremlin Resolver SG with all open egress.

### DISCUSSION THREAD

**Discussion by ramanp07** [aws-solutions/workload-discovery-on-aws#531] [Q&A]
Please could some one help me in understanding the reason for having an open egress to the internet for the security group attached to the Gremlin Resolver Lambda. The SG is provided below for easy reference and the link to it is here - [https://github.com/aws-solutions/workload-discovery-on-aws/blob/main/source/cfn/templates/gremlin-resolvers.template#L56](https://github.com/aws-solutions/workload-discovery-on-aws/blob/main/source/cfn/templates/gremlin-resolvers.template#L56)

```
GremlinResolverLambdaSg:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F1000
            reason: Needs open egress for API as it is on the internet.
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Gremlin AppSync lambda
      VpcId: !Ref VpcId
#      SecurityGroupEgress:
#        - Description: Explicit egress group locking down outbound access for HTTPS
#          CidrIp: !Ref VPCCidrBlock
#          IpProtocol: tcp
#          ToPort: !Ref NeptuneClusterPort
#          FromPort: !Ref NeptuneClusterPort
```

Thank you!
